# this file will not automatically be used. You need to pass it to kind as a parameter using --config.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: skaffold-demo
# One control plane node and two "workers".
#
# While these will not add more real compute capacity and
# have limited isolation, this can be useful for testing
# rolling updates etc.
#
# The API-server and other control plane components will be
# on the control-plane node.
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 443
    hostPort: 8443
    protocol: TCP